# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Self_Input.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess

class Ui_ScheduleWindow(object):
    def setupUi(self, SelfScheduleInput):
        SelfScheduleInput.setObjectName("SelfScheduleInput")
        SelfScheduleInput.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SelfScheduleInput)
        self.centralwidget.setObjectName("centralwidget")
        self.MedicationNameInput = self.MatchBoxLineEdit(self.centralwidget)
        self.MedicationNameInput.setGeometry(QtCore.QRect(330, 90, 271, 30))
        self.MedicationNameInput.setObjectName("MedicationNameInput")
        self.StrengthInput = self.MatchBoxLineEdit(self.centralwidget)
        self.StrengthInput.setGeometry(QtCore.QRect(330, 145, 141, 30))
        self.StrengthInput.setObjectName("StrengthInput")
        self.MedicationNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.MedicationNameLabel.setGeometry(QtCore.QRect(185, 90, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Avenir Heavy")
        font.setBold(False)
        font.setWeight(75)
        self.MedicationNameLabel.setFont(font)
        self.MedicationNameLabel.setObjectName("MedicationNameLabel")
        self.StrengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.StrengthLabel.setGeometry(QtCore.QRect(250, 145, 70, 30))
        #font = QtGui.QFont()
        #font.setBold(True)
        #font.setWeight(75)
        self.StrengthLabel.setFont(font)
        self.StrengthLabel.setObjectName("StrengthLabel")
        self.FrequencyLabel = QtWidgets.QLabel(self.centralwidget)
        self.FrequencyLabel.setGeometry(QtCore.QRect(238, 200, 80, 30))
        #font = QtGui.QFont()
        #font.setBold(True)
        #font.setWeight(75)
        self.FrequencyLabel.setFont(font)
        self.FrequencyLabel.setObjectName("FrequencyLabel")
        self.DurationLabel = QtWidgets.QLabel(self.centralwidget)
        self.DurationLabel.setGeometry(QtCore.QRect(247, 255, 75, 30))
        #font = QtGui.QFont()
        #font.setBold(True)
        #font.setWeight(75)
        self.DurationLabel.setFont(font)
        self.DurationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DurationLabel.setObjectName("DurationLabel")
        self.SelfInputComplete = QtWidgets.QPushButton(self.centralwidget)
        self.SelfInputComplete.setGeometry(QtCore.QRect(340, 365, 113, 40))
        self.SelfInputComplete.setObjectName("SelfInputComplete")
        self.SelfInputComplete.setFont(font)
        self.Self_Scheduling_Title = QtWidgets.QLabel(self.centralwidget)
        self.Self_Scheduling_Title.setGeometry(QtCore.QRect(175, 20, 450, 30))
        font = QtGui.QFont()
        font.setFamily("Avenir Heavy")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Self_Scheduling_Title.setFont(font)
        #self.Self_Scheduling_Title.setFrameShape(QtWidgets.QFrame.Box)
        self.Self_Scheduling_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Self_Scheduling_Title.setObjectName("Self_Scheduling_Title")
        self.strengthmLmg = QtWidgets.QComboBox(self.centralwidget)
        self.strengthmLmg.setGeometry(QtCore.QRect(480, 145, 104, 30))
        self.strengthmLmg.setObjectName("strengthmLmg")
        self.strengthmLmg.addItem("")
        self.strengthmLmg.addItem("")
        self.FrequencyInput = QtWidgets.QSpinBox(self.centralwidget)
        self.FrequencyInput.setGeometry(QtCore.QRect(330, 200, 48, 30))
        self.FrequencyInput.setMinimum(1)
        self.FrequencyInput.setMaximum(4)
        self.FrequencyInput.setObjectName("FrequencyInput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 200, 50, 30))
        self.label_2.setObjectName("label_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(450, 200, 135, 30))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 255, 41, 30))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 310, 41, 30))
        self.label_4.setObjectName("label_4")
        self.TimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeLabel.setGeometry(QtCore.QRect(260, 310, 55, 30))
        font = QtGui.QFont()
        font.setFamily("Avenir Heavy")
        font.setWeight(75)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeLabel.setObjectName("TimeLabel")
        self.Duration_Input = QtWidgets.QSpinBox(self.centralwidget)
        self.Duration_Input.setGeometry(QtCore.QRect(360, 255, 48, 30))
        self.Duration_Input.setMinimum(1)
        self.Duration_Input.setMaximum(100)
        self.Duration_Input.setObjectName("Duration_Input")
        self.durationDaysWeeks = QtWidgets.QComboBox(self.centralwidget)
        self.durationDaysWeeks.setGeometry(QtCore.QRect(425, 255, 104, 30))
        self.durationDaysWeeks.setObjectName("durationDaysWeeks")
        self.durationDaysWeeks.addItem("")
        self.durationDaysWeeks.addItem("")
        #SelfScheduleInput.setCentralWidget(self.centralwidget)
        #self.menubar = QtWidgets.QMenuBar(SelfScheduleInput)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        #self.menubar.setObjectName("menubar")
        #SelfScheduleInput.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SelfScheduleInput)
        self.statusbar.setObjectName("statusbar")
        #SelfScheduleInput.setStatusBar(self.statusbar)
        self.home_button = QtWidgets.QPushButton(self.centralwidget)
        self.home_button.setGeometry(QtCore.QRect(15, 15, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Avenir Heavy")
        font.setPointSize(10)
        self.home_button.setFont(font)
        self.home_button.setObjectName("home_button")
        self.time_spin_1 = QtWidgets.QTimeEdit(self.centralwidget)
        self.time_spin_1.setGeometry(QtCore.QRect(360, 310, 85, 30))
        font = QtGui.QFont()
        font.setFamily("Avenir Medium")
        font.setPointSize(10)
        self.time_spin_1.setFont(font)
        self.time_spin_1.setObjectName("time_spin_1")
        
        self.retranslateUi(SelfScheduleInput)
        QtCore.QMetaObject.connectSlotsByName(SelfScheduleInput)

    class MatchBoxLineEdit(QtWidgets.QLineEdit):
        def focusInEvent(self, e):
            try:
                subprocess.Popen(["matchbox-keyboard"])
            except FileNotFoundError:
                pass
        
        def focusOutEvent(self, e):
            subprocess.Popen(["matchbox-keyboard"]).kill()



    def retranslateUi(self, SelfScheduleInput):
        _translate = QtCore.QCoreApplication.translate
        SelfScheduleInput.setWindowTitle(_translate("SelfScheduleInput", "MainWindow"))
        self.MedicationNameLabel.setText(_translate("SelfScheduleInput", "Medication Name"))
        self.StrengthLabel.setText(_translate("SelfScheduleInput", "Strength"))
        self.FrequencyLabel.setText(_translate("SelfScheduleInput", "Frequency"))
        self.TimeLabel.setText(_translate("SelfScheduleInput", "Time"))
        self.DurationLabel.setText(_translate("SelfScheduleInput", "Duration"))
        self.SelfInputComplete.setText(_translate("SelfScheduleInput", "Finish"))
        self.Self_Scheduling_Title.setText(_translate("SelfScheduleInput", "SELF-SCHEDULING"))
        self.strengthmLmg.setItemText(0, _translate("SelfScheduleInput", "mL"))
        self.strengthmLmg.setItemText(1, _translate("SelfScheduleInput", "mg"))
        self.label_2.setText(_translate("SelfScheduleInput", "time(s)"))
        self.comboBox_3.setItemText(0, _translate("SelfScheduleInput", "every day"))
        self.comboBox_3.setItemText(1, _translate("SelfScheduleInput", "every other day"))
        self.label_3.setText(_translate("SelfScheduleInput", "for "))
        self.label_4.setText(_translate("SelfScheduleInput", "at "))
        self.durationDaysWeeks.setItemText(0, _translate("SelfScheduleInput", "day(s)"))
        self.durationDaysWeeks.setItemText(1, _translate("SelfScheduleInput", "week(s)"))
        self.home_button.setText(_translate("SelfScheduleInput", "Home"))
        
